name: 'Build and Push Container Image to Amazon ECR'
description: 'This action builds a Docker image and pushes it to Amazon ECR.'
author: 'Masashi Tsuru'

inputs:
  AWS_REGION:
    description: 'AWS region'
    required: true
  AWS_ROLE_ARN:
    description: 'AWS role ARN'
    required: true
  AWS_REGISTRY:
    description: 'AWS ECR registry'
    required: true
  IMAGE_NAME:
    description: 'Docker image name'
    required: true
  IMAGE_TAG:
    description: 'Docker image tag'
    required: true
  DOCKER_FILE_PATH:
    description: 'Path to Dockerfile'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU # to support multi-platform build building
      uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0

    - name: Set up Docker Buildx # to support multi-platform build building
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
      with:
        role-to-assume: ${{ inputs.AWS_ROLE_ARN }}
        aws-region: ${{ inputs.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
      with:
        file: ${{ inputs.DOCKER_FILE_PATH }}
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ inputs.AWS_REGISTRY }}/${{ inputs.IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha # ビルドキャッシュの参照を GitHub Actions のキャッシュに指定
        cache-to: type=gha,mode=max # ビルドキャッシュの保存を GitHub Actions のキャッシュに指定
